In [1]:
import numpy as np

# Matrix Operations

#### Arithmetic operations

In [2]:
mat_1 = np.array([
    [2, 5, 2],
    [3, 1, 0],
    [1, 4, 3]
])

mat_2 = np.array([
    [1, 4, 2],
    [2, 5, 6],
    [3, 2, 3]
])

print(mat_1, "\n")
print(mat_2, "\n")

[[2 5 2]
 [3 1 0]
 [1 4 3]] 

[[1 4 2]
 [2 5 6]
 [3 2 3]] 



In [3]:
# matrix addition

result = np.add(mat_1, mat_2)


print(result)

[[3 9 4]
 [5 6 6]
 [4 6 6]]


In [4]:
# matrix subtraction

result = np.subtract(mat_1, mat_2) # for b - a 

print(result)

[[ 1  1  0]
 [ 1 -4 -6]
 [-2  2  0]]


In [5]:
# matrix division

result = np.divide(mat_1, mat_2) # for a / b

print(result)

[[2.         1.25       1.        ]
 [1.5        0.2        0.        ]
 [0.33333333 2.         1.        ]]


In [6]:
# matrix scaler multiplication

result = 5 * mat_1

print(result)

[[10 25 10]
 [15  5  0]
 [ 5 20 15]]


In [7]:
# element wise matrix multiplication (Aij * Bij)

result = np.multiply(mat_1, mat_2)

print(result)

[[ 2 20  4]
 [ 6  5  0]
 [ 3  8  9]]


In [8]:
# matrix vector multiplication | MATRIX MULTIPLICATION
# rows of mat_1 should be equal to col of mat_2

print("Using np.dot()")
result = np.dot(mat_1, mat_2)

print(result, "\n")

print("Using np.matmul()")
print(np.matmul(mat_1, mat_2))

Using np.dot()
[[18 37 40]
 [ 5 17 12]
 [18 30 35]] 

Using np.matmul()
[[18 37 40]
 [ 5 17 12]
 [18 30 35]]


#### Determinant of a matrix

In [9]:
print(mat_2, "\n")

result = np.linalg.det(mat_2)

print(result)

[[1 4 2]
 [2 5 6]
 [3 2 3]] 

29.000000000000004


#### Transpose of matrix
- Rows -> Cols
- Cols -> Rows

In [10]:
print(mat_1, "\n")

print("Using mat_1.T")
result = mat_1.T

print(result, "\n")

print("Using np.transpose(mat_1)")
print(np.transpose(mat_1))

[[2 5 2]
 [3 1 0]
 [1 4 3]] 

Using mat_1.T
[[2 3 1]
 [5 1 4]
 [2 0 3]] 

Using np.transpose(mat_1)
[[2 3 1]
 [5 1 4]
 [2 0 3]]


#### Inverse of a matrix

In [11]:
print(mat_1, "\n")

result = np.linalg.inv(mat_1)

print(result)

[[2 5 2]
 [3 1 0]
 [1 4 3]] 

[[-0.17647059  0.41176471  0.11764706]
 [ 0.52941176 -0.23529412 -0.35294118]
 [-0.64705882  0.17647059  0.76470588]]
