# Numpy

## Contents
- __[Import numpy library](#Import-numpy-library)__
- __[Introduction and Benefits](#Introduction-and-Benefits)__
- __[Defining numpy arrays](#Define-the-array)__
- __[Data type in numpy](#Data-type-in-numpy)__
- __[Length and size of numpy array](#Length-and-size-of-numpy-array)__
- __[Copy vs View](#Copy-vs-View)__
- __[Defining array presets](#Defining-array-presets)__
- __[Get the DIMENSION of the array](#Get-the-DIMENSION-of-the-array)__
- __[Numpy Array Indexing](#Numpy-Array-Indexing)__
- __[Numpy Array Slicing](#Numpy-Array-Slicing)__
- __[Slicing Rows and Cols together](#Slicing-Rows-and-Cols-together)__
- __[Shape of array](#Get-the-SHAPE-of-the-array)__
- __[RESHAPING array](#RESHAPING-array)__
- __[Numpy Array Iterating - np.nditer()](#Numpy-Array-Iterating---np.nditer())__
- __[Numpy Axes and Operations](complexnumpy.ipynb)__
- __[Searching and Sorting in numpy arrays](#Searching-in-numpy-arrays)__
- __[numpy filter array](#numpy-filter-array)__
- __[numpy ufunc and mathematical operations](ufunc.ipynb)__
- __[Matrix Operations in numpy](matrix_operations_numpy.ipynb)__

### Import numpy library
- NumPy is usually imported under the np alias.

In [1]:
import numpy as np

### Introduction and Benefits

- NumPy is a Python library used for working with arrays.
- NumPy stands for __Numerical Python__.
- NumPy aims to provide an array object that is __up to 50x faster__ than traditional Python lists.
- NumPy is a Python library and is written partially in Python, but most of the __parts that require fast computation are written in C or C++__.
- NumPy arrays are stored at one __continuous place in memory__ unlike lists, so processes can access and manipulate them very efficiently. (locality of reference)

***

## Basics

### Define the array
- The array object in NumPy is called __ndarray__. We can create a NumPy ndarray object by using the __array()__ function.

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2, 3], [1, 4, 9]])
c = np.array(["Sunyog", "Lodhi"])
d = np.array(["sunyog", 22])
e = np.array([66, 5.11])

print(a, "\n")
print(b)

[1 2 3 4] 

[[1 2 3]
 [1 4 9]]


### Data type in numpy
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [3]:
a = np.array([1, 2, 3, 4])

# Check the data type of an array
a.dtype

# data type of array with integer and strings -"U21"
b = np.array([1, 2, "sunyog"])
b.dtype

# Convert an existing array to another type, returns a copy of string
b = a.astype("int16")

# Defining the data type of array duing initialization
# Now that we have defined the data type we cannot append string values.
c = np.array([11, 22, 33], dtype = "int")

# For i, u, f, S and U we can define size as well.
d = np.array([1, 2, 3], dtype = "int8")

a = np.array([1, 2, 3, 4, 127], dtype = "int16") # here 8 represents bits i.e. 1 byte
print(a.dtype)

int16


### Length and size of numpy array

In [4]:
a = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])

In [5]:
# get number of element
# goes deeper to count all the element, instead of just counting the number of nested arrays.
a.size

12

In [6]:
# get size
# returns size of element in byte
a.itemsize

8

In [7]:
# get total_size (memory) of the array
# returns the size of the whole array
# a.nbytes == a.size * a.itemsize
a.nbytes

96

### Copy vs View
- The copy is a new array, and the view is just a view of the original array.
- You can think of view as an another variable referencing to an array.
- Whereas copy can be thought of a variable pointing at an entirely new array.
- Think of view as viewing the original array, thus any changes from the perspective of original or view on orignal array will be visible.
- Think of copy as generating a copy of original array and moving ahead, anything done to original array or copy array won't affect each other.
- Every NumPy array has the attribute __base__ that returns __None__ if the array owns the data. Otherwise, the base  attribute refers to the __original object__.
    - __.copy()__ owns the data, so __base__ will return __None__.
    - __.view()__ does not own the data, __base__ will return __original array__

In [8]:
a = np.array([1, 2, 3, 6, 7, 8])
b = a.copy()
c = a.view()


b[0] = 69
print("After modifying the copy array")
print(f"original: {a}")
print(f"copy: {b}", "\n")

c[0] = 69
print("After modifying the view array")
print(f"original: {a}")
print(f"view: {c}", "\n")

a[-1] = 11
print("After modifying original array")
print(f"copy: {b}")
print(f"view: {c}", "\n")

#Check if Array Owns its Data
print(b.base)
print(c.base)

After modifying the copy array
original: [1 2 3 6 7 8]
copy: [69  2  3  6  7  8] 

After modifying the view array
original: [69  2  3  6  7  8]
view: [69  2  3  6  7  8] 

After modifying original array
copy: [69  2  3  6  7  8]
view: [69  2  3  6  7 11] 

None
[69  2  3  6  7 11]


In [9]:
# Example 2
change = False
arr = np.array([1, 2, 3, 4, 5, 6, 7])

def modify_np_array(arr):
    if (change):
        new_arr = arr.view()
        new_arr[0] = -1
    else:
        new_arr = arr.copy()
        new_arr[0] = -1

print(arr)
modify_np_array(arr)
print(arr)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [10]:
#Passing array on variable.
# Remember in python, ITERABLE objects are PASS BY REFERENCE

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# since pass by reference -> "brr" will also point at what "arr" is pointing at.
# Think of brr as view. 
brr = arr

# Thus changing brr will affect the original object. 
brr[0] = 69

print(arr)

[69  2  3  4  5  6  7]


### Defining array presets

In [11]:
# all zeros
np.zeros((5, 5), dtype = "int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
# all ones
np.ones((5, 4), dtype = "float32")

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [13]:
# any number of your choice
a = np.full((3, 3), 69)
a

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]])

In [14]:
# structure of another array
np.full_like((a), 9)


array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [15]:
# random decimal number
np.random.rand(3, 3)

# random integet number
np.random.randint(0, 10 ,size = (3, 3))

array([[0, 3, 5],
       [8, 8, 9],
       [9, 3, 3]])

In [16]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# Repeat each element of array n times.
arr = np.array([[1, 2, 3]])
result = np.repeat(arr, 4, axis = 0)
print(result)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


### Get the DIMENSION of the array
- A dimension in arrays is one level of array depth (nested arrays).
- When you are trying to visualize multi-dimensional array, think of them as vector instead of nested lists as concept of axes might become easier
- In other words, Level of nested list:
    - __2D: [[]]__
    - __3D: [[[]]]__
-  __0-D Arrays__: When an array only has one element.
-  __1-D Arrays__: Array which consist of one or more 0-D Arrays i.e. collection of single elements.
-  __2-D Arrays__: Array which consist of one or more 1-D Arrays.
-  __3-D Arrays__: Array which consist of one or more 2-D Arrays.
-  __Note__: A numpy array cannot contain arrays of multiple dimensions.
    - So if an array is 3D, then it'll only contain 2D arrays inside it, it cannot contain some 2D, some 1D or some 0D arrays.  


In [18]:
# 0D
zero = np.array(0)
print(zero.ndim)

#1D
one = np.array([0, 1, 2])
print(one.ndim)

#2D
two = np.array([[0, 1, 2], [3, 4, 5]])
print(two.ndim)

#3D
three = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
three = np.array([[[0, 1, 2]]])
three = np.array([[[0]]])
print(three.ndim)

# While creating an array, we can also define the number of dimensions by using the ndmin argument.
arr = np.array([1, 2, 3, 4, 5], ndmin = 4)
print(arr)

0
1
2
3
[[[[1 2 3 4 5]]]]


### Numpy Array Indexing
- Array indexing is the same as accessing an array element.

In [19]:
one = np.array([0, 1, 2, 3, 5, 8])
two = np.array([[34, 35], [36, 37]])

# Indexing depends on the dimension of the array
one[1]
# one[0, 1] will throw error. 
one[-1]
two[1, 0]

np.int64(36)

##### Access in multiple dimension

In [20]:
# array[row, col]
# 3 column and 1 row -> [x, y, z]
multiple = np.array([[
    [7, 4, 4, 2, 0],
    [2, 8, 0, 0, 0],
    [0, 9, 4, 6, 3],
    [3, 7, 4, 6, 9]
], 

[
    [0, 9, 3, 6, 2],
    [8, 8, 5, 6, 0],
    [5, 4, 3, 6, 8],
    [2, 9, 2, 69, 1]
],
         
[
    [3, 4, 2, 1, 3],
    [5, 4, 8, 5, 4],
    [7, 5, 1, 3, 1],
    [3, 9, 9, 0, 3]
]]) 
print(multiple[1, 3, 3])

69


### Numpy Array Slicing
- If we don't pass start its considered 0
- If we don't pass end its considered length of array in that dimension
- If we don't pass step its considered 1
- The result includes the start index, but excludes the end index.
- returns array

In [21]:
# array[start:end:step]
multiple = np.array([[
    [7, 4, 4, 2, 0],
    [2, 8, 0, 0, 0],
    [0, 9, 4, 6, 3],
    [3, 7, 4, 6, 9]
], 

[
    [0, 9, 3, 6, 2],
    [8, 8, 5, 6, 0],
    [5, 4, 3, 6, 8],
    [2, 9, 2, 69, 1]
],
         
[
    [3, 4, 2, 1, 3],
    [5, 4, 8, 5, 4],
    [7, 5, 1, 3, 1],
    [3, 9, 9, 0, 3]
]]) 

multiple[0::2]
multiple[:]
multiple[2:-2:2]
multiple[0:1]


array([[[7, 4, 4, 2, 0],
        [2, 8, 0, 0, 0],
        [0, 9, 4, 6, 3],
        [3, 7, 4, 6, 9]]])

### Slicing Rows and Cols together
- When you want piece of array

In [22]:
multiple = np.arange(1, 10).reshape(3,3)
print(multiple, "\n")

print(multiple[1:3, 0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[4 5]
 [7 8]]


In [23]:

multiple = np.array([[
    [7, 4, 4, 2, 0],
    [2, 8, 0, 0, 0],
    [0, 9, 4, 6, 3],
    [3, 7, 4, 6, 9]
], 

[
    [0, 9, 3, 6, 2],
    [8, 8, 5, 6, 0],
    [5, 4, 3, 6, 8],
    [2, 9, 2, 69, 1]
],
         
[
    [3, 4, 2, 1, 3],
    [5, 4, 8, 5, 4],
    [7, 5, 1, 3, 1],
    [3, 9, 9, 0, 3]
]]) 

multiple[1:2, 1:3, 1:4]


multiple [-1, 1:5, 1:4]

array([[4, 8, 5],
       [5, 1, 3],
       [9, 9, 0]])

In [24]:
multiple.shape

(3, 4, 5)

#### Practice question
<pre>
1, 1, 1, 1, 1
1, 0, 0, 0, 1
1, 0, 9, 0, 1
1, 0, 0, 0, 1
1, 1, 1, 1, 1
</pre>

In [25]:
ans = np.ones((5, 5), dtype = "int")

z = np.zeros((3,3))
z[1, 1] = 9

# ans[row, col]
ans[1:-1, 1:-1] = z

print(ans)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Get the SHAPE of the array
- The shape of an array is the number of elements in each dimension.
- Returns a tuple with each index indicating the number of element in each dimension.
- Nested arrays in Multidimensional must have same shape.
    - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
- The example below returns (2, 3), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 3.
- In the example below at __index 2__ we have __value 2__, so we can say that __3rd ( 2 + 1 rd)__ dimension has __2 elements__.

In [26]:
# get shape
one = np.array([1, 2, 3, 4, 5])
two = np.array([
    [1, 2, 3], 
    [5, 6, 7]
])
three = np.array([
    [[0, 1,],
     [2, 3], 
     [4, 5]],
    
    [[6, 7], 
     [8, 9], 
     [10, 11]]
])

print(one.shape)
print(two.shape)
print(three.shape)

(5,)
(2, 3)
(2, 3, 2)


#### RESHAPING array
- Reshaping means changing the shape of an array.
- The shape of an array is the number of elements in each dimension.
- By reshaping we can add or remove dimensions or change number of elements in each dimension.
- returns original array so it's a view
- Good rule of thumb to prevent error:
    - __if N = num of element:__
    - __then reshape(x, y):__
    - __such that x * y = N__ 

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


oneD_to_threeD = arr.reshape(3, 2, 2)
oneD_to_TwoD = arr.reshape(6, 2)

print(oneD_to_TwoD)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


#### Flattening the array (n-D to 1D)
- Flattening array means converting a multidimensional array into a 1D array.
- This can be achieved by passing __-1__ in reshape().

In [28]:
three = np.array([[[0, 1,],[2, 3], [4, 5]], [[6, 7], [8, 9], [10, 11]]])
one = three.reshape(-1)
print(one)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Numpy Array Iterating - np.nditer()

#### 1D

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6])

for item in arr:
    print(item)

1
2
3
4
5
6


#### 2D
- You may notice we are using __n loops for n-dimensional__ array.
- Instead of using n-loops we can use, numpy built-in method __np.nditer(array)__

In [30]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
for item in arr:
    for deeper_item in item:
        print(deeper_item)

1
2
3
4
5
6


#### Using np.nditer() in for loop
- With __np.nditer(three)__, we can loop over the sclaer quantities of multidimensional array. 

In [31]:
three = np.array([[[0, 1,],[2, 3], [4, 5]], [[6, 7], [8, 9], [10, 11]]])
for item in np.nditer(three):
    print(item)



0
1
2
3
4
5
6
7
8
9
10
11


#### np.ndenumerate()

In [32]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for serial, item in np.ndenumerate(arr):
  print(serial, item)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### [Numpy Axes and Operations](complexnumpy.ipynb)

### Searching in numpy arrays
- where() -> returns the index of the target element.

In [33]:
a = np.arange(1, 25)
print(a)

print(np.where(a == 22))

# returns the index of even number
print(np.where(a % 2 == 0))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(array([21]),)
(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]),)


#### searchsorted()
- performs a binary search in the array.
- returns the index where the specified value would be inserted to maintain the search order.
- The searchsorted() method is assumed to be used on sorted arrays.
- By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [34]:
arr = np.array([3, 4, 5, 6, 7, 8, 9])

x = np.searchsorted(arr, 7)
y = np.searchsorted(arr, 7, side = 'right')

print(x)
print(y)


4
5


#### Sorting numpy arrays

In [35]:
# sort 1d arrays
arr = np.random.randint(0, 10, size = 10)
print(arr)
print(np.sort(arr))


[2 4 6 8 0 1 9 5 9 6]
[0 1 2 4 5 6 6 8 9 9]


In [36]:
# Sort 2d arrays
brr = np.random.randint(0, 20, size = (4, 4))
print(brr, "\n")
print(np.sort(brr))

[[14 19  9 19]
 [13 19  9  7]
 [ 5 16  7  9]
 [16  0  8  8]] 

[[ 9 14 19 19]
 [ 7  9 13 19]
 [ 5  7  9 16]
 [ 0  8  8 16]]


In [37]:
a = np.array(["sunyog", 1, 2, "apple"])

print(np.sort(a))

# Seems like it is coverting all the elements to string. -> U21

['1' '2' 'apple' 'sunyog']


#### numpy filter array
- Getting some elements out of an existing array and creating a new array out of them based on some condition is called filtering.
- filter will return true or false (__b__ here)
- and we can use filter to print the elements of __a__ that passes the filter (__result__ here)

In [38]:
a = np.arange(1, 25)
a = a * 3

# filter
b = a % 2 == 0


# get the filtered results
result = (a[b])

print(result)

[ 6 12 18 24 30 36 42 48 54 60 66 72]


In [39]:
# Explanation of what is happening above.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

result_arr = []

for item in arr:
    if (item % 2 == 0):
        result_arr.append(True)
    else:
        result_arr.append(False)


# This is a feature specific to numpy, not really possible in core python.
f_result = arr[result_arr]



***

## [numpy ufunc and mathematical operations](ufunc.ipynb)

***

## [Matrix Operations in numpy](matrix_operations_numpy.ipynb)