In [1]:
import numpy as np

# numpy ufunc

- ufuncs stands for __"Universal Functions"__.
- NumPy functions that operate on the ndarray object.
- ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
- ufuncs also take additional arguments, like:
    - __where__ boolean array or condition defining where the operations should take place.
    - __dtype__ defining the return type of elements.
    - __out__ output array where the return value should be copied.

### What is Vectorization?
    - Converting iterative statements into a vector based operation is called vectorization.
    - It is faster as modern CPUs are optimized for such operations.

#### Creating our own universal function (ufunc)
- Create the function like we normally do.
- Then we add that function to numpy ufunc library.
    - We use __frompyfunc()__ to achieve this
    - The frompyfunc() method takes the following arguments:
        - __function__ - the name of the function.
        - __inputs__ - the number of input arguments (arrays).
        - __outputs__ - the number of output arrays.

In [2]:
def add_this(x, y):
    result = x + y
    return result

u_add_this = np.frompyfunc(add_this, 2, 1)

one = [1, 2, 3, 4, 5]
two = [6, 7, 8, 9, 0]


# Notice how normal python operation would be performed here.
print(add_this(one, two))

# Notice how a universal function works differently compared to normal python function. 
print(u_add_this(one, two))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[7 9 11 13 5]


#### Check if a function is ufunc

In [3]:
print(type(u_add_this))
print(type(np.concatenate))

<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


***

### Mathematical operation on numpy arrays
- __There are also universal function (ufunc).__

#### Addition

In [4]:
one = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
two = np.array([3, 4, 2, 1, 7, 8]).reshape(2, 3)

result = one + two # performs on axis 0
# '+' operator is similar to:
result_2 = np.add(one, two)

print(result, "\n")
print(result_2, "\n")
print(type(np.add))

[[ 4  6  5]
 [ 5 12 14]] 

[[ 4  6  5]
 [ 5 12 14]] 

<class 'numpy.ufunc'>


#### Subtraction

In [5]:
one = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
two = np.array([3, 4, 2, 1, 7, 8]).reshape(2, 3)

result = two - one
result_2 = np.subtract(two, one)

print(result, "\n")
print(result_2, "\n")
print(type(np.subtract))

[[ 2  2 -1]
 [-3  2  2]] 

[[ 2  2 -1]
 [-3  2  2]] 

<class 'numpy.ufunc'>


#### Multiplication

In [6]:
one = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
two = np.array([3, 4, 2, 1, 7, 8]).reshape(2, 3)

result = one * two
result_2 = np.multiply(one, two)

print(result, "\n")
print(result_2, "\n")
print(type(np.multiply))

[[ 3  8  6]
 [ 4 35 48]] 

[[ 3  8  6]
 [ 4 35 48]] 

<class 'numpy.ufunc'>


#### Division

In [7]:
one = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
two = np.array([3, 4, 2, 1, 7, 8]).reshape(2, 3)

result = two / one
result_2 = np.divide(two, one)

print(result, "\n")
print(result_2, "\n")
print(type(np.divide))

[[3.         2.         0.66666667]
 [0.25       1.4        1.33333333]] 

[[3.         2.         0.66666667]
 [0.25       1.4        1.33333333]] 

<class 'numpy.ufunc'>


#### Modulus

In [8]:
one = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
two = np.array([3, 4, 2, 1, 7, 8]).reshape(2, 3)

#np.remainder() also does the same operation.
result = two % one
result_2 = np.mod(two, one)

print(result, "\n")
print(result_2, "\n")
print(type(np.mod))

[[0 0 2]
 [1 2 2]] 

[[0 0 2]
 [1 2 2]] 

<class 'numpy.ufunc'>


#### divmod

In [9]:
# returns quotient and remainder in 2 different arrays.

one = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
two = np.array([3, 4, 2, 1, 7, 8]).reshape(2, 3)

result = np.divmod(two, one)

print(result, "\n")
print(type(np.mod))

(array([[3, 2, 0],
       [0, 1, 1]]), array([[0, 0, 2],
       [1, 2, 2]])) 

<class 'numpy.ufunc'>


#### absolute

In [10]:
# returns the absolute value of a number
one = np.array([1, -2, -3, 4, -5, -6]).reshape(2, 3)

result = np.absolute(one)

print(result)

[[1 2 3]
 [4 5 6]]


#### Rounding decimals

In [11]:
one = np.array([
    [4.33481217, 7.27126761, 8.40728221,],
    [9.11116345, 8.90629127, 9.49564157],
    [2.71087867, 5.85665841, 8.63645183]
])
print(one)

[[4.33481217 7.27126761 8.40728221]
 [9.11116345 8.90629127 9.49564157]
 [2.71087867 5.85665841 8.63645183]]


In [12]:
# np.trunc(): returns ROUNDED but FLOAT
# np.fix() also does the same thing. 
result = np.trunc(one)
print(result)

[[4. 7. 8.]
 [9. 8. 9.]
 [2. 5. 8.]]


In [13]:
# np.around()
# The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.
# round off to 1 decimal point, 3.16666 is 3.2
result = np.around(one)
print(result)

[[4. 7. 8.]
 [9. 9. 9.]
 [3. 6. 9.]]


In [14]:
# floor
# The floor() function rounds off decimal to nearest lower integer.
result = np.floor(one)
print(result)

[[4. 7. 8.]
 [9. 8. 9.]
 [2. 5. 8.]]


In [15]:
# ceil
# The ceil() function rounds off decimal to nearest upper integer.
result = np.ceil(one)
print(result)

[[ 5.  8.  9.]
 [10.  9. 10.]
 [ 3.  6.  9.]]


#### Logarithmic

In [16]:
arr = np.arange(1, 10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [17]:
#np.log2()
# Log at Base 2
# Find log at base 2 of all elements of an array:

result = np.log2(arr)

print(result)

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [18]:
#np.log10()
# Log at Base 10
# find log at base 2 of all elements of an array

result = np.log10(arr)

print(result)

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [19]:
#np.log()
# Log at Base e
# find log at base 3 of all elements of an array

result  = np.log(arr)

print(result)

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [20]:
# There is no numpy function for log at any base.
# Instead use python's function => math.log()

#### summations, products and differences

In [21]:
arr = np.arange(1, 10)
brr = np.arange(1, 10).reshape(3,3) # 2-dimensional array

print(arr, "\n")
print(brr, "\n")

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [22]:
# SUMMATION returns the sum of all the elements of the array

print(arr.sum())
print(brr.sum(axis = 0))

45
[12 15 18]


In [23]:
# CUMMULATIVE-SUM
# Cummulative sum means partially adding the elements in array.

arr.cumsum()
# 1, 2+1, 3+2+1, 4+3+2+1...

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [24]:
#PRODUCTS
# returns the product of all the elements of the array. 

print(arr.prod())
print(brr.prod(axis = 1))


362880
[  6 120 504]


In [25]:
# CUMMULATIVE PRODUCT
# Cummulative product means taking the product partially.

print(arr.cumprod())
# 1, 2*1, 3*2*1, 4*3*2*1...

[     1      2      6     24    120    720   5040  40320 362880]


In [26]:
# DIFFERENCE
drr = np.array([1, 4, 3, 8, 2, 0])

print(np.diff(drr))
# xi = x(i+1) - xi

# You can also perform np.diff() on repead by defining 'n' attribute. 
print(np.diff(drr, n = 3))

[ 3 -1  5 -6 -2]
[ 10 -17  15]


#### LCM and GCD

In [27]:
# LCM - The Lowest Common Multiple is the smallest number that is a common multiple of two numbers.

# np.lcm() will return the lcm of only 2 numbers
print(np.lcm(2, 3))
print(np.lcm(13, 17))

# To find the lcm of more than 2 numbers use reduce() function
# The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension.

arr = np.array([1, 3, 5, 7, 13, 17])

result = np.lcm.reduce(arr)

print(result)

6
221
23205


In [28]:
# GCD - Greatest Common Divisor | Greatest Common Denominator | Highest Common Factor (HCF)
# The biggest number that is a common factor of both of the numbers.

# np.gcd() will return the gcd of only 2 numbers
print(np.gcd(24, 9))

# To find the gcd of more than 2 numbers use reduce() function

print(np.gcd.reduce([120, 60, 4 ]))


3
4


#### Set operation in numpy
- the set arrays should only be 1-D arrays.

In [29]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

# We can create a 'set array' of above array by using np.unique()
u_arr = np.unique(arr)

print(u_arr)

[1 2 3 4 5 6 7]


In [30]:
a = np.arange(1, 10)
b = np.arange(7, 15)

print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[ 7  8  9 10 11 12 13 14]


In [31]:
# Finding the union of 2 np arrays
c = np.union1d(a, b)

print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [32]:
# Finding the intersection of 2 np arrays

c = np.intersect1d(a, b)

print(c)

[7 8 9]


In [33]:
# Finding the difference of 2 np arrays

c = np.setdiff1d(a, b)
# A - (A n B)
print(c)

# Note: the setdiff1d() method takes an optional argument assume_unique, which if set to True can speed up computation. 
# It should always be set to True when dealing with sets.
c = np.setdiff1d(b, a, assume_unique = True)
# B - (A n B)
print(c)

[1 2 3 4 5 6]
[10 11 12 13 14]


In [34]:
# Finding the symmetric difference of 2 np arrays
# (A u B) - A n B)

c = np.setxor1d(a, b)
print(c)

[ 1  2  3  4  5  6 10 11 12 13 14]
